### PR TITLE
Implemented FileChooser API

### PR DESCRIPTION
**Pull request by celestialhorizon**
Hello, due to urgent need of FileChooser api, i implemented this on my fork. Maybe this is a bit of good news for you guys but im not sure how can i merge my contribution.. do i need to create tests too for this FileChooser? If yes then its okay to decline my pull request and i will add tests later.

And also this requires chrome revision 674921 too.. im not sure you guys want this pull request for now or not

And also you can tell me if my code is not good enough for merging..

Thanks

### CODE REVIEW

**Review by Mattwmaster58 — COMMENTED** [review]
Hi, thanks for your changes here. (Unfortunately,)? It looks like the file chooser has already been implemented on the `pup2.1.1` which you can install with `pip install git+https://github.com/pyppeteer/pyppeteer2.git@pup2.1.1`. If you have any issues feel free to hit any of us up in the Matrix channel: https://matrix.to/#/!ScehqfCSdMAUhZoeDC:matrix.org?via=matrix.org

**Comment by celestialhorizon** [comment]
Oh :( i didnt see that coming.. My mistake.. i didnt see that branch

**Comment by Mattwmaster58** [comment]
It's fine, it's not very clear unless you sift through the issues. Hopefully we can get it merged to dev so it's a little more obvious

**Comment by celestialhorizon** [comment]
By the way, i see that now the browser is not automatically downloaded? Can you tell me which api that i need to use to download it at runtime? instead of running pyppeteer2-install..

**Comment by Mattwmaster58** [comment]
That seems like a bug, I will look into it. Closing this as it's not needed.

**Pull request closed without merging**
