### PR TITLE
Update websockets to 10 version wich compatible with python 3.10

### PR DESCRIPTION
**Pull request by heckad**

### CODE REVIEW

**Comment by Mattwmaster58** [comment]
Should help with #327

**Comment by JensTimmerman** [comment]
updating websockets to 10 fails for me:
```
  File "/home/jens/workplace/pa/lib/screenshotter.py", line 27, in <module>
    print('data:image/png;base64,' + screenshot('http://example,com'))
  File "/home/jens/workplace/pa/lib/screenshotter.py", line 22, in screenshot
    out = asyncio.get_event_loop().run_until_complete(main(url))
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/jens/workplace/pa/lib/screenshotter.py", line 8, in main
    browser = await launch(ignoreHTTPSErrors=True, logLevel='DEBUG')
  File "/home/jens/.local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/jens/.local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 169, in launch
    self.connection = Connection(self.browserWSEndpoint, self._loop, connectionDelay, )
  File "/home/jens/.local/lib/python3.10/site-packages/pyppeteer/connection.py", line 43, in __init__
    self._ws = websockets.client.connect(
  File "/home/jens/.local/lib/python3.10/site-packages/websockets/imports.py", line 92, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'

```

edit, sorry this was with pyppetteer 0.2.5; updating to 0.2.6 and applying this fix got me a step further.

**Comment by bravier** [comment]
Hi @Mattwmaster58,
Can you release a new 0.2.7 version of Pyppeteer containing this commit for people using Python 3.10?
Thank you.

**Comment by Mattwmaster58** [comment]
This is problematic as Websockets 10 eliminates support for python 3.6 which is currently ~16% of those using the package

**Comment by Mattwmaster58** [comment]
Since this project is basically in limp mode for lack of maintainers with time, I decided to drop 3.6 support for 3.10 users. I have pushed 1.0.0 that fixes this

**Pull request merged**
