### PR TITLE
Improve progress bar for chromium download

### PR DESCRIPTION
**Pull request by Zebradil**
This shows progress in bytes, scaled as needed.

### CODE REVIEW

**Comment by Mattwmaster58** [comment]
Hey @Zebradil, thanks for the PR. Unfortunately, something similar to this has already been implemented on the `pup2.1.1` branch which uses `tqdm`'s autoscaling for proper units.

**Comment by Zebradil** [comment]
It's the following code, to be precise:

```python
    progress_bar = tqdm(
        total=int(file_req.getheader('Content-Length', 0)),
        unit_scale=True,
        file=os.devnull if NO_PROGRESS_BAR else None,
    )
```

I suggest also using `unit` and `unit_divisor` parameters for correct size calculation.

Apart from that, it seems like `file=os.devnull` doesn't work as intended. `tqdm` expects something with `write` method, but `str` doesn't have one. To disable progress bar, there is an intended parameter `disabled`.

**Comment by Mattwmaster58** [comment]
Ok, I just tried out this patch and it seems to be working as intended. I do like seeing MB/s instead of Mit/s (which is what is happening on the `pup2.1.1` branch). Since `pup2.1.1` will become the next version, it would be a little annoying to use as so much has changed, so if you could work off that branch instead that would be great (the relevant lines to change can be found in [this file](https://github.com/pyppeteer/pyppeteer/blob/8a811c7a7313d8994ea354edf1e1c095866f7df6/pyppeteer/browser_fetcher.py)).

**Comment by Zebradil** [comment]
Thanks for checking that out! I’ll prepare a new PR shortly.

**Comment by Zebradil** [comment]
#113 is created instead of this one

**Pull request closed without merging**
