### PR TITLE
Remove urllib3.disable_warnings

### PR DESCRIPTION
**Pull request by ninoseki**
Remove `urllib3.disable_warnings` and use `ca_certs` provided by `certifi` because using an insecure connection is a bad idea in terms of security.

- Ref. https://github.com/miyakogi/pyppeteer/issues/258#issuecomment-563075764

### CODE REVIEW

**Comment by Mattwmaster58** [comment]
I believe this is actually not required anymore because Python >= 3.7.4 has patched the root issue that was causing this problem. I'm not sure what versions of 3.6 are affected/fixed. I'll see if I can find a reference for that.

**Comment by Mattwmaster58** [comment]
Here's the reference: https://github.com/urllib3/urllib3/issues/1682#issuecomment-533311857
It mentions that 3.6 _cannot_ be fixed, so this PR may have some merit there. @ninoseki Could you base your work off the pup2.1.1 branch? That way we won't have to mess around when it comes to merging pup2.1.1 to dev.

**Comment by ninoseki** [comment]
Sorry for lack of my research and thank you for your comments.
I will make a PR to `pup2.1.1 branch` to use certifi in `browser_fetcher.py`.

**Comment by Mattwmaster58** [comment]
No problem! The only reason I had the knowledge is that I had to thoroughly investigate a very similar issue recently. 

Thank you for your willingness to base your work on the `pup2.1.1` branch. 

Feel free to request a review from me when you're done.

**Comment by Mattwmaster58** [comment]
Superceded by #76

**Pull request closed without merging**
